# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v3

      - name: Get Node.js 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Show node version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Verify formatting
        run: npm run lint --if-present

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build --if-present
    
    
